"""Team -> subreddit mapping. Verify exact subreddit names before large-scale runs."""

TEAM_SUBREDDITS = {
    "Atlanta Hawks": "AtlantaHawks",
    "Boston Celtics": "bostonceltics",
    "Brooklyn Nets": "GoNets",
    "Charlotte Hornets": "CharlotteHornets",
    "Chicago Bulls": "chicagobulls",
    "Cleveland Cavaliers": "clevelandcavs",
    "Dallas Mavericks": "mavericks",
    "Denver Nuggets": "denvernuggets",
    "Detroit Pistons": "DetroitPistons",
    "Golden State Warriors": "warriors",
    "Houston Rockets": "rockets",
    "Indiana Pacers": "pacers",
    "LA Clippers": "LAClippers",
    "Los Angeles Lakers": "lakers",
    "Memphis Grizzlies": "memphisgrizzlies",
    "Miami Heat": "heat",
    "Milwaukee Bucks": "MkeBucks",
    "Minnesota Timberwolves": "timberwolves",
    "New Orleans Pelicans": "NOLAPelicans",
    "New York Knicks": "NYKnicks",
    "Oklahoma City Thunder": "Thunder",
    "Orlando Magic": "OrlandoMagic",
    "Philadelphia 76ers": "sixers",
    "Phoenix Suns": "suns",
    "Portland Trail Blazers": "ripcity",
    "Sacramento Kings": "kings",
    "San Antonio Spurs": "NBASpurs",
    "Toronto Raptors": "torontoraptors",
    "Utah Jazz": "UtahJazz",
    "Washington Wizards": "washingtonwizards",
}

# Nicknames/aliases used to detect which team(s) an article is about via text
# matching (articles aren't scoped to a single subreddit like Reddit posts are).
TEAM_ALIASES = {
    "Atlanta Hawks": ["Hawks"],
    "Boston Celtics": ["Celtics"],
    "Brooklyn Nets": ["Nets"],
    "Charlotte Hornets": ["Hornets"],
    "Chicago Bulls": ["Bulls"],
    "Cleveland Cavaliers": ["Cavaliers", "Cavs"],
    "Dallas Mavericks": ["Mavericks", "Mavs"],
    "Denver Nuggets": ["Nuggets"],
    "Detroit Pistons": ["Pistons"],
    "Golden State Warriors": ["Warriors"],
    "Houston Rockets": ["Rockets"],
    "Indiana Pacers": ["Pacers"],
    "LA Clippers": ["Clippers"],
    "Los Angeles Lakers": ["Lakers"],
    "Memphis Grizzlies": ["Grizzlies"],
    "Miami Heat": ["Heat"],
    "Milwaukee Bucks": ["Bucks"],
    "Minnesota Timberwolves": ["Timberwolves", "Wolves"],
    "New Orleans Pelicans": ["Pelicans"],
    "New York Knicks": ["Knicks"],
    "Oklahoma City Thunder": ["Thunder"],
    "Orlando Magic": ["Magic"],
    "Philadelphia 76ers": ["76ers", "Sixers"],
    "Phoenix Suns": ["Suns"],
    "Portland Trail Blazers": ["Trail Blazers", "Blazers"],
    "Sacramento Kings": ["Kings"],
    "San Antonio Spurs": ["Spurs"],
    "Toronto Raptors": ["Raptors"],
    "Utah Jazz": ["Jazz"],
    "Washington Wizards": ["Wizards"],
}
